name: youtube_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  google_fonts: 6.2.1
  http: ^1.4.0
  json_annotation: ^4.9.0
  json_serializable: ^6.9.5

dev_dependencies:
  build_runner: ^2.5.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
