name: youtube_clone
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: 2.4.1
  google_fonts: 6.2.1
  http: ^1.4.0
  json_annotation: 4.8.1
  

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: 2.4.5
  json_serializable: 6.7.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
